services:
  db:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    command: serve

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    restart: always

  fastapi:
      build:
        context: .
        dockerfile: src/Dockerfile
      container_name: fastapi
      restart: always
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file:
        - .env

volumes:
  ollama_data: