"""create task table

Revision ID: 8a262d697019
Revises: 9a5896b2d84f
Create Date: 2025-06-14 14:49:36.237126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a262d697019"
down_revision: Union[str, None] = "9a5896b2d84f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "tasks",
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("SINGLE", "SUBSCRIBE", name="tasktype"),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum("GLOBAL", "PERSONAL", name="taskscope"),
            nullable=False,
        ),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bot_id"],
            ["bots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")

    task_type = sa.Enum("SINGLE", "SUBSCRIBE", name="tasktype")
    task_scope = sa.Enum("GLOBAL", "PERSONAL", name="taskscope")
    task_type.drop(op.get_bind())
    task_scope.drop(op.get_bind())
    # ### end Alembic commands ###
