"""update task table

Revision ID: da68fa5c6ab3
Revises: 489fb03ce592
Create Date: 2025-06-16 23:27:42.507192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da68fa5c6ab3"
down_revision: Union[str, None] = "489fb03ce592"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


    op.add_column(
        "bots", sa.Column("is_authorized", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.drop_column("bots", "last_seen")
    op.drop_constraint("tasks_bot_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "bots", ["bot_id"], ["id"], ondelete="CASCADE"
    )

    op.drop_column("tasks", "type")
    op.drop_column("tasks", "post_id")
    task_type = sa.Enum("SINGLE", "SUBSCRIBE", name="tasktype")
    task_type.drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_type = sa.Enum("SINGLE", "SUBSCRIBE", name="tasktype")
    task_type.create(op.get_bind())

    op.add_column(
        "tasks",
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "type",
            postgresql.ENUM("SINGLE", "SUBSCRIBE", name="tasktype"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint("tasks_bot_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_bot_id_fkey"), "tasks", "bots", ["bot_id"], ["id"]
    )
    op.add_column(
        "bots",
        sa.Column(
            "last_seen",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("bots", "is_authorized")
    # ### end Alembic commands ###
