"""update task table

Revision ID: 489fb03ce592
Revises: 8a262d697019
Create Date: 2025-06-16 13:53:26.218134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "489fb03ce592"
down_revision: Union[str, None] = "8a262d697019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    task_status = sa.Enum("NEW", "IN_PROGRESS", "DONE", "FAILED", name="taskstatus")
    task_status.create(op.get_bind())

    op.add_column(
        "tasks",
        sa.Column("status", task_status, nullable=False, server_default=sa.text("'NEW'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "status")
    task_status = sa.Enum("NEW", "IN_PROGRESS", "DONE", "FAILED", name="taskstatus")
    task_status.drop(op.get_bind())
    # ### end Alembic commands ###
