"""update bot table

Revision ID: 58bdcebdc185
Revises: da68fa5c6ab3
Create Date: 2025-06-18 15:14:02.023098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58bdcebdc185"
down_revision: Union[str, None] = "da68fa5c6ab3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bots", sa.Column("phone_code_hash", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "phone_code_hash")
    # ### end Alembic commands ###
